name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - name: Install Playwright
        run: npx playwright install --with-deps
      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run test:ci
